### ISSUE TITLE
Does not connect to open WiFi after connecting to WPA

### ISSUE THREAD

**Issue by AVHon** [overrider/wireless#3]
The script connects to WPA networks fine, and I can easily switch between them.However, it cannot connect to an open network after being used to connect to an open network.

I can manually connect to open networks after using this script to connect to WPA networks. Once I have connected to an open network, this script can switch between other open networks and to WPA networks. After switching to a WPA network, the script again looses the ability to connect to open wireless networks.

**Comment by overrider** [comment]
I think you have solved this issue so ill close this report. Thanks...
